#!/bin/sh

TARGET=aarch64-none-linux-android

export COMMON=--builddir=dist/$TARGET
export COMPILE="--with-ghc=${TARGET}-ghc
                --with-ghc-pkg=${TARGET}-ghc-pkg
                --with-gcc=${TARGET}-clang
                --with-ld=${TARGET}-ld
                --hsc2hs-options=--cross-compile"

# we want to disable library stripping for android; this would call the xcode toolchain strip command,
# which simply fails.
export CONFIG="--configure-option=--host=${TARGET} --disable-shared --disable-library-stripping"

exec "`dirname $0`/common-cross-cabal" "$@"
