#!/bin/bash

source linux-android-toolchain.config

ARCH=arm64

exec ${ANDROID_NDK}/toolchains/llvm/prebuilt/${HOST_ARCH}/bin/clang \
     -target ${ARCH}-none-linux-android \
     --sysroot=${ANDROID_NDK}/platforms/android-${API_VERSION}/arch-${ARCH} \
     --gcc-toolchain=${ANDROID_NDK}/toolchains/aarch64-linux-android-${GCC_VERSION}/prebuilt/${HOST_ARCH}/bin \
     -fuse-ld=$(which aarch64-linux-android-ld) \
     -isysroot ${ANDROID_NDK}/platforms/android-${API_VERSION}/arch-${ARCH} \
     "$@"
