#!/bin/bash

source linux-android-toolchain.config

ARCH=arm64

exec ${ANDROID_NDK}/toolchains/aarch64-linux-android-${GCC_VERSION}/prebuilt/${HOST_ARCH}/bin/aarch64-linux-android-ld \
     --sysroot=${ANDROID_NDK}/platforms/android-${API_VERSION}/arch-${ARCH} \
     -L${ANDROID_NDK}/toolchains/aarch64-linux-android-${GCC_VERSION}/prebuilt/${HOST_ARCH}/lib/gcc/aarch64-linux-android/4.9.x/ \
     "$@"

