#!/bin/bash

source linux-android-toolchain.config

ARCH=arm
TARGET=arm-linux-androideabi

# NOTE: There is an added v7 in the -target; this *is* stupid!

exec ${ANDROID_NDK}/toolchains/llvm/prebuilt/${HOST_ARCH}/bin/clang \
     -target ${ARCH}v7-none-linux-androideabi \
     --sysroot=${ANDROID_NDK}/platforms/android-${API_VERSION}/arch-${ARCH} \
     --gcc-toolchain=${ANDROID_NDK}/toolchains/${TARGET}-${GCC_VERSION}/prebuilt/${HOST_ARCH}/bin \
     -fuse-ld=$(which ${TARGET}-ld) \
     -isysroot ${ANDROID_NDK}/platforms/android-${API_VERSION}/arch-${ARCH} \
     "$@"
