#!/bin/bash

source linux-android-toolchain.config

ARCH=arm
TARGET=arm-linux-androideabi

exec ${ANDROID_NDK}/toolchains/${TARGET}-${GCC_VERSION}/prebuilt/${HOST_ARCH}/bin/${TARGET}-ld \
     --sysroot=${ANDROID_NDK}/platforms/android-${API_VERSION}/arch-${ARCH} \
     -L${ANDROID_NDK}/toolchains/${TARGET}-${GCC_VERSION}/prebuilt/${HOST_ARCH}/lib/gcc/${TARGET}/4.9.x/ \
     "$@"

