#!/bin/bash

targets="arm-linux-gnueabihf armv7-linux-androideabi aarch64-linux-android aarch64-apple-darwin14 x86_64-apple-darwin14"
commands="clang ld nm ar ranlib cabal"

for target in $targets; do
	for command in $commands; do
		ln -s wrapper $target-$command
	done
done